[package]
name = "parallel-dsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
fundsp = "0.16.0"
midir = "0.9.1"
ringbuf = "0.3.3"
hound = "3.5.1"
